### ISSUE TITLE
mvp-hq in fullscreen mode prevents League of Legends.exe from loading 

### ISSUE THREAD

**Issue by elgatov** [haasn/mpvhq#12]
It seems if you have mpv-hq running in fullscreen League of Legends window will not run, it is necessary to exit fullscreen in mpv-hq to prevent this.

**Comment by CamilleScholtz** [comment]
Sounds more like a window manager/LoL issue than a mpvhq one to me..

**Comment by haasn** [comment]
Not an mpvhq-specific issue. As mentioned, this sounds very unrelated to mpv in general.
