### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by SolarAquarion** [haasn/mpvhq#7]
[489/491] Linking build/libmpv.so
/usr/bin/ld: warning: libx265.so.43, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libutvideo.so.15.0.2, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfdk-aac.so.0, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `x265_encoder_open_43'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacDecoder_DecodeFrame'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacDecoder_AncDataInit'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacEncEncode'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacDecoder_Close'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`x265_param_free'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `x265_max_bit_depth'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacDecoder_SetParam'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `x265_encoder_headers'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacDecoder_ConfigRaw'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `x265_param_alloc'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`x265_encoder_encode'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacEncoder_SetParam'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`x265_encoder_close'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `CCodec::DeleteInstance(CCodec*)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacEncClose'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `CCodec::CreateInstance(unsigned int, char const*)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`x265_param_parse'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacDecoder_GetStreamInfo'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacEncOpen'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacDecoder_Fill'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`x265_param_default_preset'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `aacEncInfo'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to`aacDecoder_Open'
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so: undefined reference to `x265_picture_init'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/solaraquarion/vlc-clang-git/mpvhq-git/src/mpvhq/build'
Build failed
 -> task in 'mpv' failed (exit status 1): 
    {task 140338538431040: cprogram main-fn-unix.c.13.o,audio.c.12.o,audio_buffer.c.12.o,chmap.c.12.o,chmap_sel.c.12.o,fmt-conversion.c.12.o,format.c.12.o,mixer.c.12.o,ad_lavc.c.12.o,ad_spdif.c.12.o,dec_audio.c.12.o,af.c.12.o,af_bs2b.c.12.o,af_center.c.12.o,af_channels.c.12.o,af_convert24.c.12.o,af_convertsignendian.c.12.o,af_delay.c.12.o,af_drc.c.12.o,af_dummy.c.12.o,af_equalizer.c.12.o,af_export.c.12.o,af_extrastereo.c.12.o,af_format.c.12.o,af_hrtf.c.12.o,af_karaoke.c.12.o,af_ladspa.c.12.o,af_lavcac3enc.c.12.o,af_lavfi.c.12.o,af_lavrresample.c.12.o,af_pan.c.12.o,af_rubberband.c.12.o,af_scaletempo.c.12.o,af_sinesuppress.c.12.o,af_sub.c.12.o,af_surround.c.12.o,af_sweep.c.12.o,af_volume.c.12.o,filter.c.12.o,tools.c.12.o,window.c.12.o,ao.c.12.o,ao_alsa.c.12.o,ao_jack.c.12.o,ao_lavc.c.12.o,ao_null.c.12.o,ao_oss.c.12.o,ao_pcm.c.12.o,ao_pulse.c.12.o,ao_rsound.c.12.o,pull.c.12.o,push.c.12.o,av_common.c.12.o,av_log.c.12.o,codecs.c.12.o,encode_lavc.c.12.o,common.c.12.o,tags.c.12.o,msg.c.12.o,playlist.c.12.o,version.c.12.o,codec_tags.c.12.o,demux.c.12.o,demux_cue.c.12.o,demux_disc.c.12.o,demux_edl.c.12.o,demux_lavf.c.12.o,demux_libass.c.12.o,demux_mf.c.12.o,demux_mkv.c.12.o,demux_mkv_timeline.c.12.o,demux_playlist.c.12.o,demux_raw.c.12.o,demux_rar.c.12.o,demux_subreader.c.12.o,demux_tv.c.12.o,ebml.c.12.o,packet.c.12.o,timeline.c.12.o,cmd_list.c.12.o,cmd_parse.c.12.o,event.c.12.o,input.c.12.o,ipc.c.12.o,keycodes.c.12.o,bstr.c.12.o,charset_conv.c.12.o,dispatch.c.12.o,json.c.12.o,ring.c.12.o,rendezvous.c.12.o,m_config.c.12.o,m_option.c.12.o,m_property.c.12.o,options.c.12.o,parse_commandline.c.12.o,parse_configfile.c.12.o,path.c.12.o,audio.c.12.o,client.c.12.o,command.c.12.o,configfiles.c.12.o,discnav.c.12.o,loadfile.c.12.o,main.c.12.o,misc.c.12.o,lua.c.12.o,osd.c.12.o,playloop.c.12.o,screenshot.c.12.o,scripting.c.12.o,sub.c.12.o,video.c.12.o,ai_alsa1x.c.12.o,ai_oss.c.12.o,audio_in.c.12.o,cache.c.12.o,cache_file.c.12.o,cookies.c.12.o,dvb_tune.c.12.o,frequencies.c.12.o,rar.c.12.o,stream.c.12.o,stream_avdevice.c.12.o,stream_bluray.c.12.o,stream_cdda.c.12.o,stream_dvb.c.12.o,stream_dvd.c.12.o,stream_dvd_common.c.12.o,stream_dvdnav.c.12.o,stream_edl.c.12.o,stream_file.c.12.o,stream_lavf.c.12.o,stream_memory.c.12.o,stream_mf.c.12.o,stream_null.c.12.o,stream_pvr.c.12.o,stream_rar.c.12.o,stream_smb.c.12.o,stream_tv.c.12.o,tv.c.12.o,tvi_dummy.c.12.o,tvi_v4l2.c.12.o,ass_mp.c.12.o,dec_sub.c.12.o,draw_bmp.c.12.o,find_subfiles.c.12.o,img_convert.c.12.o,osd.c.12.o,osd_libass.c.12.o,sd_ass.c.12.o,sd_lavc.c.12.o,sd_lavc_conv.c.12.o,sd_lavf_srt.c.12.o,sd_microdvd.c.12.o,sd_movtext.c.12.o,sd_srt.c.12.o,csputils.c.12.o,fmt-conversion.c.12.o,image_writer.c.12.o,img_format.c.12.o,mp_image.c.12.o,mp_image_pool.c.12.o,sws_utils.c.12.o,vaapi.c.12.o,vdpau.c.12.o,vdpau_mixer.c.12.o,dec_video.c.12.o,vaapi.c.12.o,vd_lavc.c.12.o,vf.c.12.o,vf_buffer.c.12.o,vf_crop.c.12.o,vf_delogo.c.12.o,vf_dlopen.c.12.o,vf_dsize.c.12.o,vf_eq.c.12.o,vf_expand.c.12.o,vf_flip.c.12.o,vf_format.c.12.o,vf_gradfun.c.12.o,vf_hqdn3d.c.12.o,vf_lavfi.c.12.o,vf_mirror.c.12.o,vf_noformat.c.12.o,vf_noise.c.12.o,vf_pullup.c.12.o,vf_rotate.c.12.o,vf_scale.c.12.o,vf_screenshot.c.12.o,vf_stereo3d.c.12.o,vf_sub.c.12.o,vf_unsharp.c.12.o,vf_vavpp.c.12.o,vf_vdpaupp.c.12.o,vf_yadif.c.12.o,aspect.c.12.o,bitmap_packer.c.12.o,dither.c.12.o,filter_kernels.c.12.o,gl_common.c.12.o,gl_hwdec.c.12.o,gl_hwdec_vaglx.c.12.o,gl_hwdec_vdpau.c.12.o,gl_lcms.c.12.o,gl_osd.c.12.o,gl_utils.c.12.o,gl_video.c.12.o,gl_wayland.c.12.o,gl_x11.c.12.o,vo.c.12.o,vo_caca.c.12.o,vo_image.c.12.o,vo_lavc.c.12.o,vo_null.c.12.o,vo_opengl.c.12.o,vo_opengl_cb.c.12.o,vo_vaapi.c.12.o,vo_vdpau.c.12.o,vo_wayland.c.12.o,vo_x11.c.12.o,vo_xv.c.12.o,wayland_common.c.12.o,buffer.c.12.o,memfile.c.12.o,win_state.c.12.o,x11_common.c.12.o,terminal-unix.c.12.o,io.c.12.o,timer.c.12.o,timer-linux.c.12.o,threads.c.12.o,semaphore_osx.c.12.o,subprocess-posix.c.12.o,ta.c.12.o,ta_talloc.c.12.o,ta_utils.c.12.o -> mpv}
['/usr/lib/hardening-wrapper/bin/cc', '-Wl,-O1,--sort-common,--as-needed,-z,relro', '-pthread', '-Wl,-z,noexecstack', 'player/main-fn-unix.c.13.o', 'audio/audio.c.12.o', 'audio/audio_buffer.c.12.o', 'audio/chmap.c.12.o', 'audio/chmap_sel.c.12.o', 'audio/fmt-conversion.c.12.o', 'audio/format.c.12.o', 'audio/mixer.c.12.o', 'audio/decode/ad_lavc.c.12.o', 'audio/decode/ad_spdif.c.12.o', 'audio/decode/dec_audio.c.12.o', 'audio/filter/af.c.12.o', 'audio/filter/af_bs2b.c.12.o', 'audio/filter/af_center.c.12.o', 'audio/filter/af_channels.c.12.o', 'audio/filter/af_convert24.c.12.o', 'audio/filter/af_convertsignendian.c.12.o', 'audio/filter/af_delay.c.12.o', 'audio/filter/af_drc.c.12.o', 'audio/filter/af_dummy.c.12.o', 'audio/filter/af_equalizer.c.12.o', 'audio/filter/af_export.c.12.o', 'audio/filter/af_extrastereo.c.12.o', 'audio/filter/af_format.c.12.o', 'audio/filter/af_hrtf.c.12.o', 'audio/filter/af_karaoke.c.12.o', 'audio/filter/af_ladspa.c.12.o', 'audio/filter/af_lavcac3enc.c.12.o', 'audio/filter/af_lavfi.c.12.o', 'audio/filter/af_lavrresample.c.12.o', 'audio/filter/af_pan.c.12.o', 'audio/filter/af_rubberband.c.12.o', 'audio/filter/af_scaletempo.c.12.o', 'audio/filter/af_sinesuppress.c.12.o', 'audio/filter/af_sub.c.12.o', 'audio/filter/af_surround.c.12.o', 'audio/filter/af_sweep.c.12.o', 'audio/filter/af_volume.c.12.o', 'audio/filter/filter.c.12.o', 'audio/filter/tools.c.12.o', 'audio/filter/window.c.12.o', 'audio/out/ao.c.12.o', 'audio/out/ao_alsa.c.12.o', 'audio/out/ao_jack.c.12.o', 'audio/out/ao_lavc.c.12.o', 'audio/out/ao_null.c.12.o', 'audio/out/ao_oss.c.12.o', 'audio/out/ao_pcm.c.12.o', 'audio/out/ao_pulse.c.12.o', 'audio/out/ao_rsound.c.12.o', 'audio/out/pull.c.12.o', 'audio/out/push.c.12.o', 'common/av_common.c.12.o', 'common/av_log.c.12.o', 'common/codecs.c.12.o', 'common/encode_lavc.c.12.o', 'common/common.c.12.o', 'common/tags.c.12.o', 'common/msg.c.12.o', 'common/playlist.c.12.o', 'common/version.c.12.o', 'demux/codec_tags.c.12.o', 'demux/demux.c.12.o', 'demux/demux_cue.c.12.o', 'demux/demux_disc.c.12.o', 'demux/demux_edl.c.12.o', 'demux/demux_lavf.c.12.o', 'demux/demux_libass.c.12.o', 'demux/demux_mf.c.12.o', 'demux/demux_mkv.c.12.o', 'demux/demux_mkv_timeline.c.12.o', 'demux/demux_playlist.c.12.o', 'demux/demux_raw.c.12.o', 'demux/demux_rar.c.12.o', 'demux/demux_subreader.c.12.o', 'demux/demux_tv.c.12.o', 'demux/ebml.c.12.o', 'demux/packet.c.12.o', 'demux/timeline.c.12.o', 'input/cmd_list.c.12.o', 'input/cmd_parse.c.12.o', 'input/event.c.12.o', 'input/input.c.12.o', 'input/ipc.c.12.o', 'input/keycodes.c.12.o', 'misc/bstr.c.12.o', 'misc/charset_conv.c.12.o', 'misc/dispatch.c.12.o', 'misc/json.c.12.o', 'misc/ring.c.12.o', 'misc/rendezvous.c.12.o', 'options/m_config.c.12.o', 'options/m_option.c.12.o', 'options/m_property.c.12.o', 'options/options.c.12.o', 'options/parse_commandline.c.12.o', 'options/parse_configfile.c.12.o', 'options/path.c.12.o', 'player/audio.c.12.o', 'player/client.c.12.o', 'player/command.c.12.o', 'player/configfiles.c.12.o', 'player/discnav.c.12.o', 'player/loadfile.c.12.o', 'player/main.c.12.o', 'player/misc.c.12.o', 'player/lua.c.12.o', 'player/osd.c.12.o', 'player/playloop.c.12.o', 'player/screenshot.c.12.o', 'player/scripting.c.12.o', 'player/sub.c.12.o', 'player/video.c.12.o', 'stream/ai_alsa1x.c.12.o', 'stream/ai_oss.c.12.o', 'stream/audio_in.c.12.o', 'stream/cache.c.12.o', 'stream/cache_file.c.12.o', 'stream/cookies.c.12.o', 'stream/dvb_tune.c.12.o', 'stream/frequencies.c.12.o', 'stream/rar.c.12.o', 'stream/stream.c.12.o', 'stream/stream_avdevice.c.12.o', 'stream/stream_bluray.c.12.o', 'stream/stream_cdda.c.12.o', 'stream/stream_dvb.c.12.o', 'stream/stream_dvd.c.12.o', 'stream/stream_dvd_common.c.12.o', 'stream/stream_dvdnav.c.12.o', 'stream/stream_edl.c.12.o', 'stream/stream_file.c.12.o', 'stream/stream_lavf.c.12.o', 'stream/stream_memory.c.12.o', 'stream/stream_mf.c.12.o', 'stream/stream_null.c.12.o', 'stream/stream_pvr.c.12.o', 'stream/stream_rar.c.12.o', 'stream/stream_smb.c.12.o', 'stream/stream_tv.c.12.o', 'stream/tv.c.12.o', 'stream/tvi_dummy.c.12.o', 'stream/tvi_v4l2.c.12.o', 'sub/ass_mp.c.12.o', 'sub/dec_sub.c.12.o', 'sub/draw_bmp.c.12.o', 'sub/find_subfiles.c.12.o', 'sub/img_convert.c.12.o', 'sub/osd.c.12.o', 'sub/osd_libass.c.12.o', 'sub/sd_ass.c.12.o', 'sub/sd_lavc.c.12.o', 'sub/sd_lavc_conv.c.12.o', 'sub/sd_lavf_srt.c.12.o', 'sub/sd_microdvd.c.12.o', 'sub/sd_movtext.c.12.o', 'sub/sd_srt.c.12.o', 'video/csputils.c.12.o', 'video/fmt-conversion.c.12.o', 'video/image_writer.c.12.o', 'video/img_format.c.12.o', 'video/mp_image.c.12.o', 'video/mp_image_pool.c.12.o', 'video/sws_utils.c.12.o', 'video/vaapi.c.12.o', 'video/vdpau.c.12.o', 'video/vdpau_mixer.c.12.o', 'video/decode/dec_video.c.12.o', 'video/decode/vaapi.c.12.o', 'video/decode/vd_lavc.c.12.o', 'video/filter/vf.c.12.o', 'video/filter/vf_buffer.c.12.o', 'video/filter/vf_crop.c.12.o', 'video/filter/vf_delogo.c.12.o', 'video/filter/vf_dlopen.c.12.o', 'video/filter/vf_dsize.c.12.o', 'video/filter/vf_eq.c.12.o', 'video/filter/vf_expand.c.12.o', 'video/filter/vf_flip.c.12.o', 'video/filter/vf_format.c.12.o', 'video/filter/vf_gradfun.c.12.o', 'video/filter/vf_hqdn3d.c.12.o', 'video/filter/vf_lavfi.c.12.o', 'video/filter/vf_mirror.c.12.o', 'video/filter/vf_noformat.c.12.o', 'video/filter/vf_noise.c.12.o', 'video/filter/vf_pullup.c.12.o', 'video/filter/vf_rotate.c.12.o', 'video/filter/vf_scale.c.12.o', 'video/filter/vf_screenshot.c.12.o', 'video/filter/vf_stereo3d.c.12.o', 'video/filter/vf_sub.c.12.o', 'video/filter/vf_unsharp.c.12.o', 'video/filter/vf_vavpp.c.12.o', 'video/filter/vf_vdpaupp.c.12.o', 'video/filter/vf_yadif.c.12.o', 'video/out/aspect.c.12.o', 'video/out/bitmap_packer.c.12.o', 'video/out/dither.c.12.o', 'video/out/filter_kernels.c.12.o', 'video/out/gl_common.c.12.o', 'video/out/gl_hwdec.c.12.o', 'video/out/gl_hwdec_vaglx.c.12.o', 'video/out/gl_hwdec_vdpau.c.12.o', 'video/out/gl_lcms.c.12.o', 'video/out/gl_osd.c.12.o', 'video/out/gl_utils.c.12.o', 'video/out/gl_video.c.12.o', 'video/out/gl_wayland.c.12.o', 'video/out/gl_x11.c.12.o', 'video/out/vo.c.12.o', 'video/out/vo_caca.c.12.o', 'video/out/vo_image.c.12.o', 'video/out/vo_lavc.c.12.o', 'video/out/vo_null.c.12.o', 'video/out/vo_opengl.c.12.o', 'video/out/vo_opengl_cb.c.12.o', 'video/out/vo_vaapi.c.12.o', 'video/out/vo_vdpau.c.12.o', 'video/out/vo_wayland.c.12.o', 'video/out/vo_x11.c.12.o', 'video/out/vo_xv.c.12.o', 'video/out/wayland_common.c.12.o', 'video/out/wayland/buffer.c.12.o', 'video/out/wayland/memfile.c.12.o', 'video/out/win_state.c.12.o', 'video/out/x11_common.c.12.o', 'osdep/terminal-unix.c.12.o', 'osdep/io.c.12.o', 'osdep/timer.c.12.o', 'osdep/timer-linux.c.12.o', 'osdep/threads.c.12.o', 'osdep/semaphore_osx.c.12.o', 'osdep/subprocess-posix.c.12.o', 'ta/ta.c.12.o', 'ta/ta_talloc.c.12.o', 'ta/ta_utils.c.12.o', '-o', '/home/solaraquarion/vlc-clang-git/mpvhq-git/src/mpvhq/build/mpv', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-lrsound', '-lX11', '-lsmbclient', '-lrubberband', '-ldl', '-lavdevice', '-lvdpau', '-ljack', '-lz', '-lasound', '-ldvdread', '-lswresample', '-lenca', '-llcms2', '-lcdio_paranoia', '-lcdio_cdda', '-lcdio', '-lm', '-lv4l2', '-llua5.1', '-lm', '-ldvdnav', '-lpthread', '-lXext', '-lXv', '-lavfilter', '-lbs2b', '-lass', '-lXrandr', '-lXinerama', '-lavutil', '-lavcodec', '-lavformat', '-lswscale', '-lXss', '-lGL', '-lbluray', '-lcaca', '-lm', '-lguess', '-lpulse', '-lva', '-lwayland-client', '-lwayland-cursor', '-lxkbcommon', '-lwayland-egl', '-lwayland-client', '-lEGL', '-ljpeg', '-lva-x11', '-lva', '-lrt']

**Comment by haasn** [comment]
```
/usr/bin/ld: warning: libx265.so.43, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libutvideo.so.15.0.2, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfdk-aac.so.0, needed by /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/libavcodec.so, not found (try using -rpath or -rpath-link)
```

Fix your dependencies.
